version: '3'
services:

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=myname
      - AWS_SECRET_ACCESS_KEY=myS3Pass
      - HOSTNAME_EXTERNAL=localhost
      - USE_SSL=false
      - DEBUG=1

