version: '2'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379

  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.25.4.192
      KAFKA_CREATE_TOPICS: "pets:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
